### ISSUE TITLE
[BUG] Issues with compression

### ISSUE THREAD

**Issue by TokMor** [OmnissiahZelos/omnimatter#168]
Regular chemical plants do not appear to be generating compacted versions. 
https://cdn.discordapp.com/attachments/361628919675355148/704813153103511592/unknown.png

Additionally some recipes don't appear to be flagged as being built in compacted buildings, such as liquid-plastic-3
https://cdn.discordapp.com/attachments/361628919675355148/704816412451012658/unknown.png

**Comment by adamcirillo** [comment]
Have confirmed bug using current DEV Branch. Not sure how to find out what's causing bug have looked at some of the functions can't seem to see if anything is wrong

**Comment by Pezzawinkle** [comment]
Im struggling to relicate that first one with minimal mods.
However, i have managed to narrow down that second one to only be for recipes with no solids. Will keep digging until i find the cause.

**Comment by Pezzawinkle** [comment]
Part 2 has been fixed and is on dev, will need more time to find the building not compressed bug

**Comment by Pezzawinkle** [comment]
think i found a fix for part 1, these are both now published in Dev

**Comment by TokMor** [comment]
Looks pretty solid, but I did find an issue still. 

Here is a non-compressed recipe
![](https://cdn.discordapp.com/attachments/361628919675355148/707580725351809064/unknown.png)

This is how it looks compressed though. 

![](https://cdn.discordapp.com/attachments/361628919675355148/707580637229613096/unknown.png)

**Comment by Pezzawinkle** [comment]
interesting, it seems im trading issues with that fix, ill need to keep digging
